---
- name: "Hammerspoon | MacOSX | Install Hammerspoon"
  community.general.homebrew_cask:
    name: hammerspoon
    state: present
- name: "Hammerspoon | MacOSX | Configure Hammerspoon Home"
  community.general.osx_defaults:
    domain: org.hammerspoon.Hammerspoon
    key: MJConfigFile
    value: "{{ xdg_config.path }}/hammerspoon/init.lua"
    state: present
