---
- name: DotFiles Config
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Create Config Files
      ansible.builtin.import_tasks: pre_tasks/create_config_files.yml
      tags:
        - always
    - name: Setup Git
      ansible.builtin.import_tasks: pre_tasks/setup_git.yml
      tags:
        - always
  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{% if ansible_run_tags | list == ['all'] %}{{ default_roles | reject('in', exclude_roles | default([])) | list }}{% else %}{{ (default_roles | select('in', ansible_run_tags) | list) + (ansible_run_tags | reject('in', default_roles) | reject('equalto', 'all') | list) }}{% endif %}"
      tags:
        - always
    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always
    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
