---
- name: DotFiles Config
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Create Config Files
      ansible.builtin.import_tasks: pre_tasks/create_config_files.yml
      tags:
        - always
    - name: Setup Rust
      ansible.builtin.import_tasks: pre_tasks/setup_rust.yml
      tags:
        - always
  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always
    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always
    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
