" start Vundle plugin manager
set nocompatible                " I WILL BE V-IMPROVED
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" core plugins
Bundle 'VundleVim/Vundle.vim'
Bundle 'flazz/vim-colorschemes'

" main plugins
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'myusuf3/numbers.vim'
Bundle 'christoomey/vim-tmux-navigator'

" lang specific plugins
Bundle 'vim-ruby/vim-ruby'
Bundle 'kchmck/vim-coffee-script'
Bundle 'heartsentwined/vim-emblem'
Bundle 'slim-template/vim-slim.git'
Bundle 'airblade/vim-gitgutter'

" experimental plugins
Bundle 'vim-airline/vim-airline'
Bundle 'vim-airline/vim-airline-themes'
Bundle 'tpope/vim-endwise'
Bundle 'ervandew/supertab'
Bundle 'jiangmiao/auto-pairs'
Bundle 'kien/ctrlp.vim'
Bundle 'miyakogi/conoline.vim'
Bundle 'vim-scripts/gitignore'
Plugin 'garbas/vim-snipmate'

" works with vim-snipmate
Plugin 'honza/vim-snippets'

"TODO
"get multicursor, ruby block

call vundle#end()            " required

syntax enable
filetype plugin indent on    " required

" place general settings in config/base
source $HOME/dotfiles/vim/config/mappings.vim
source $HOME/dotfiles/vim/config/base.vim

" place plugin specific settings in config/plugins/<NAME-OF-PLUGIN>.vim
source $HOME/dotfiles/vim/config/plugins/vim-colorschemes.vim
source $HOME/dotfiles/vim/config/plugins/vim-tmux-navigator.vim
source $HOME/dotfiles/vim/config/plugins/vim-airline.vim
source $HOME/dotfiles/vim/config/plugins/conoline.vim
source $HOME/dotfiles/vim/config/plugins/ctrlp.vim
