---
- name: Check if asdf is available
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.asdf/asdf.sh"
  register: asdf_exists
- name: "gpg | MacOSX | Install gpg"
  community.general.homebrew:
    name: gpg
    state: present
