---
- name: "ZSH | MacOSX | Install Zsh"
  community.general.homebrew:
    name: zsh
    state: present
  notify: Change Shell
- name: "ZSH | MacOSX | Install Zinit"
  community.general.homebrew:
    name: zinit
    state: present
- name: "ZSH | MacOSX | Set zsh as default shell"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
