---
# Ordered list of layouts to use by layout key
# (default tall, wide, fullscreen, and column).
layouts:
  - tall
  - fullscreen
  - wide
  - column

# First mod
mod1:
  - option
  - shift

# Second mod
mod2:
  - option
  - command

# # Third mod (not used by default).
# mod3:

# # Fourth mod (not used by default).
# mod4:

# # The max number of windows that may be visible on a screen at one time before
# # additional windows are minimized. A value of 0 disables the feature.
# window-max-count: 0

# Boolean flag for whether or not to add margins betwen windows (default false).
window-margins: true

# # Boolean flag for whether or not to set window margins if there is only one
# # window on the screen, assuming window margins are enabled (default false).
# smart-window-margins: false

# The size of the margins between windows (in px, default 0).
window-margin-size: 5

# # # The smallest height that a window can be sized to regardless of its layout
# # frame (in px, default 0).
# window-minimum-height: 0

# # The smallest width that a window can be sized to regardless of its layout
# # frame (in px, default 0)
# window-minimum-width: 0

# List of bundle identifiers for applications to either be automatically
# floating or automatically tiled based on floating-is-blacklist (default []).
floating:
  - "org.alacritty"
  - "app.ytmd"

# Boolean flag determining behavior of the floating list.
# true if the applications should be floating and all others tiled.
# false if the applications should be tiled and all others floating
# (default true).
floating-is-blacklist: true

# true if screen frames should exclude the status bar. false if the screen
# frames should include the status bar (default false).
ignore-menu-bar: false

# true if windows smaller than a 500px square should be floating by default
# (default true)

float-small-windows: false
# true if the mouse should move position to the center of a window when it
# becomes focused (default false). Note that this is largely incompatible with
# focus-follows-mouse.
mouse-follows-focus: false

# true if the windows underneath the mouse should become focused as the mouse
# moves (default false).
# Note that this is largely incompatible with mouse-follows-focus
focus-follows-mouse: false

# true if dragging and dropping windows on to each other should swap their
# positions (default false).
mouse-swaps-windows: false

# true if changing the frame of a window with the mouse should update the layout
# to accommodate the change (default false).
# Note that not all layouts will be able to respond to the change.
mouse-resizes-windows: false

# true to display the name of the layout when a new layout is selected
# (default true).
enables-layout-hud: true

# true to display the name of the layout when moving to a new space
# (default true).
enables-layout-hud-on-space-change: true

# true to get updates to beta versions of the software (default false).
use-canary-build: false

# true to insert new windows into the first position and false to insert new
# windows into the last position (default false).
new-windows-to-main: false

# true to automatically move to a space when throwing a window to it
# (default true).
follow-space-thrown-windows: true

# The integer percentage of the screen dimension to increment and decrement main
# pane ratios by (default 5).
window-resize-step: 5

# Padding to apply between windows and the left edge of the screen
# (in px, default 0).
# screen-padding-left: 0

# Padding to apply between windows and the right edge of the screen
# (in px, default 0).
# screen-padding-right: 0

# Padding to apply between windows and the top edge of the screen
# (in px, default 0).
screen-padding-top: 5

# Padding to apply between windows and the bottom edge of the screen
# (in px, default 0).
screen-padding-bottom: 10

# true to maintain layout state across application executions (default true).
restore-layouts-on-launch: true

# true to display some optional debug information in the layout HUD
# (default false).
debug-layout-info: false

# true to disable screen padding on in-built display (default false).
disable-screen-padding-on-inbuilt: false

# Automatically quit and reopen Amethyst.
relaunch-amethyst:
  mod: mod2
  key: r
