---
- name: Kill Dock
  ansible.builtin.command: killall Dock
  changed_when: true
- name: Kill SystemUIServer
  ansible.builtin.command: killall SystemUIServer
  changed_when: true
- name: Restart Finder
  ansible.builtin.command: killall Finder
  changed_when: true
