---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config
- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists
- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }} | Link dotfiles config"
  ansible.builtin.command:
    cmd: stow --target={{ ansible_env.HOME }} alacritty --verbose=2
    chdir: "{{ ansible_env.HOME }}/dotfiles"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  become: false
